export const ADD_POST = 'POST_ACTION:ADD_POST';
export const SET_ALL_POSTS = 'POST_ACTION:SET_ALL_POSTS';
export const LOAD_MORE_POSTS = 'POST_ACTION:LOAD_MORE_POSTS';
export const TOGGLE_LIKE = 'POST_ACTION:TOGGLE_LIKE';
export const SET_EXPANDED_POST = 'POST_ACTION:SET_EXPANDED_POST';
export const ADD_COMMENT = 'POST_ACTION:ADD_COMMENT';
export const UPDATE_POST = 'PUT_ACTION:UPDATE_POST';
export const SET_EXPANDED_UPDATE_POST = 'POST_ACTION:SET_EXPANDED_UPDATE_POST';
